### ISSUE TITLE
Coordinates not understood with non-dot decimal separators

### ISSUE THREAD

**Issue by tYYGH** [magikcypress/grav-plugin-leaflet#8]
The French language uses “,” as the decimal separator. As a consequence, when I write this:

```
leaflet:
    lat: 47.22536
    lng: -1.52307
    lat_marker: 47.22536
    lng_marker: -1.52307
```

numbers are read, and given to Javascript as 47,22536 and -1,52307 ⇒ This fails.

To make “leaflet” work, I had to change to this:

```
leaflet:
    lat: '47.22536'
    lng: '-1.52307'
    lat_marker: '47.22536'
    lng_marker: '-1.52307'
```

(strings instead of numbers)

Please either change all the examples accordingly (using strings), or keep numbers but force the locale to `en_US` or the like while inserting these numbers into the Javascript.
